### ISSUE TITLE
inc not working with \t symbols

### ISSUE THREAD

**Issue by Abyss-z94** [Ino42O/Dialog-Center-Text#2]
`new string[512];
	format(string, sizeof(string), "\\c{FFFFFF}Welcome to {ebfde3}%s{FFFFFF}\n\n\
									{b00d3b}Ban Ra:{666666}\n{bbbbbb}Mat Hang\tTrong kho(Toi da)\tGia Ban Ra\tSan xuat/1 tieng\n\n\
									{768e04}Thu Mua:{666666}\n{bbbbbb}Mat Hang\tTrong kho(Toi da)\tGia Mua Vao\tTieu thu/1 tieng\n\n\
									", Industry[idx][ind_Name]);
ShowPlayerDialog(playerid, DIALOG_NOTHING, DIALOG_STYLE_MSGBOX, "Industry", string, "Ban Do", "Dong Lai");`

![sa-mp-036](https://cloud.githubusercontent.com/assets/18276778/21983327/4f9af894-dc23-11e6-8a53-07eaa96f2b18.png)

**Comment by Ino-Bagaric** [comment]
Thanks for feedback, i will try in less possible time solve issue

**Comment by Ino-Bagaric** [comment]
Sorry for late comment, but this can't be solved, you will have to use it without tab (\t)
